NAS/urls.py
from django.contrib import admin
from django.urls import path, include

from classroom.views import studentsignup, teachersignup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/student/', studentsignup, name='student_signup'),
    path('accounts/signup/teacher/', teachersignup, name='teacher_signup'),
]

classroom/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    home,
    StudentAssignmentListView,
    take_assignment,
    submit_answer,
    AssignmentListView,
    AssignmentCreateView,
    AssignmentDeleteView,
    AssignmentUpdateView,
    view_result,
    view_answer,
    question_add,
    question_change,
    QuestionDeleteView,
)

urlpatterns = [
    path("", home, name="home"),
    path(
        "students/",
        include(
            (
                [
                    path(
                        "", StudentAssignmentListView.as_view(), name="assignment_list"
                    ),
                    path(
                        "assignment/<int:pk>/", take_assignment, name="take_assignment"
                    ),
                    path(
                        "assignment/<int:pk>/submit",
                        submit_answer,
                        name="submit_answer",
                    ),
                ],
                "classroom",
            ),
            namespace="students",
        ),
    ),
    path(
        "teacher/",
        include(
            (
                [
                    path(
                        "", AssignmentListView.as_view(), name="assignment_change_list"
                    ),
                    path(
                        "assignment/add/",
                        AssignmentCreateView.as_view(),
                        name="assignment_add",
                    ),
                    path(
                        "assignment/<int:pk>/",
                        AssignmentUpdateView.as_view(),
                        name="assignment_change",
                    ),
                    path(
                        "assignment/<int:pk>/delete/",
                        AssignmentDeleteView.as_view(),
                        name="assignment_delete",
                    ),
                    # path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
                    path(
                        "assignment/<int:pk>/result/", view_result, name="view_result"
                    ),
                    path(
                        "assignment/<int:assignments_pk>/result/<int:asn_pk>/",
                        view_answer,
                        name="view_result_student",
                    ),
                    path(
                        "assignment/<int:pk>/question/add/",
                        question_add,
                        name="question_add",
                    ),
                    path(
                        "assignment/<int:assignment_pk>/question/<int:question_pk>/",
                        question_change,
                        name="question_change",
                    ),
                    path(
                        "assignment/<int:assignment_pk>/question/<int:question_pk>/delete/",
                        QuestionDeleteView.as_view(),
                        name="question_delete",
                    ),
                ],
                "classroom",
            ),
            namespace="teachers",
        ),
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Online Assignment Submission"
admin.site.site_title = "OAS Admin Login"
admin.site.index_title = "Welcome to Online Assignment Submission Portal"

templates/teachers/assignment_add_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Assignment Add Form {% endblock title %}

{% block content %}
    <br>
    <h2 class="mb-3">Add a new assignment</h2>
    <div class="row">
        <div class="col-md-6 col-sm-8 col-12">  
            <form method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit' class="btn btn-success">Save</button>
                <a href="{% url 'teachers:assignment_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
            </form>
        </div>
    </div>
{% endblock content %}

templates/teachers/assignment_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{ assignments.name }} {% endblock title %}

{% block content %}
    <div class="row mb-3">
        <div class="col-md-6 col-sm-8 col-12">
            <h3 class="mb-3">My Assignments</h3>
            <form method = 'post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit' class="btn btn-success">Save changes</button>
                <a href="{% url 'teachers:assignment_change_list'%}" class="btn btn-outline-secondary" role="button">Nevermind</a>
                <a href="{% url 'teachers:assignment_delete' assignments.pk %}" class="btn btn-danger float-right" role="button">Delete</a>
            </form>
            <br>
        </div>
    </div>
        <strong>Question</strong>
        <br>
        <div class="card">
            <div class="list-group list-group-flush list-group-formset">
                {% for question in questions %}
                    <div class="list-group-item">
                        <div class="row">
                            <div class="col-10">
                                <a href="{% url 'teachers:question_change' assignments.pk question.pk %}">{{ question.text }}</a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="list-group-item text-center">
                        You haven't created any questions. <a href="{% url 'teachers:question_add' assignments.pk%}">Add questions.</a>
                    </div>
                {% endfor %}
        </div>
        <div class="card-footer">
            <a href="{% url 'teachers:question_add' assignments.pk %}" class="btn btn-primary btn-sm">Add question</a>
        </div>
{% endblock content %}

templates/teachers/assignment_change_list.html
{% extends 'base.html' %}

{% block title %} My Assignments {% endblock title %}

{% block content %}
    
    <h2 class="mb-3">Assignments</h2>
    <a href="{% url 'teachers:assignment_add' %}" class="btn btn-primary" role="button">Add Assignment</a></p>
    <div class='card'>
        <table class="table mb-0">
            <thead>
                <tr>
                    <th>Assignment</th>
                    <th>Subject</th>
                    <th>Semester</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for assignment in assignments %}
                    <tr>
                        <td class="align-middle"><a href="{% url 'teachers:assignment_change' assignment.pk%}">{{ assignment.name }}</a></td>
                        <td class="align-middle">{{ assignment.subject }}</td>
                        <td class="align-middle">{{ assignment.subject.semester }}</td>
                        <td class="align-middle"><a href="{% url 'teachers:view_result' assignment.pk %}" class="btn btn-primary" role="button">Result</a></td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>You haven't created any Assignments</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

templates/teachers/assignment_delete_confirm.html
{% extends 'base.html' %}

{% block title %} Delete {{ assignments.name }} ? {% endblock title %}

{% block content %}
    <h3 class="mb-3">Confirm deletion</h3>
    <br>
    Are you sure you want to delete the quiz <strong>"{{ assignments.name }}"</strong>? There is no going back.
    <br><br>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, I'm sure</button>
        <a href="{% url 'teachers:assignment_change' assignments.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
    </form>
{% endblock content %}

templates/teachers/question_add_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Question add form {% endblock title %}

{% block content %}
    <h3 class="mb-3">My Assignments</h3>
    <strong>{{ assignments.name }}</strong>
    <br><br>
    Add a new question:
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'teachers:assignment_change' assignments.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
    </form>
{% endblock content %}

templates/teachers/question_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags crispy_forms_filters %}

{% block title %} Question Change Form {% endblock title %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'teachers:assignment_change' assignments.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
        <a href="{% url 'teachers:question_delete' assignments.pk question.pk %}" class="btn btn-danger float-right" role="button">Delete</a>
    </form>
{% endblock content %}

templates/teachers/question_delete_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Question Delete Form {% endblock title %}

{% block content %}
    <h3 class="mb-3">Confirm deletion</h3>
    Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There is no going back.
    <br><br>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Yes, I'm sure</button>
        <a href="{% url 'teachers:question_change' assignments.pk question.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
    </form>
{% endblock content %}

templates/teachers/question_upload.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Upload</button>
    <a href="{% url 'teachers:assignment_change' assignments.pk %}" role="button" class="btn btn-outline-secondary">Nevermind</a>
  </form>

  
{% endblock %}

templates/teachers/view_answers.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{ assignments.name }} {% endblock title %}

{% block content %}
    <br>
    {% for qq in answered_image %}
        {% if qq.answer_image %}
            <a href="/media/{{ qq.answer_image }}" download><img src="/media/{{ qq.answer_image }}" class="img-responsive" style="width:32%; height:60%;"/></a>
        {% endif %}
        {% if qq.answer_file %}
            <a href="/media/{{ qq.answer_file }}" download>{{ qq.filename }}</a>
        {% endif %}
    {% empty %}

    {% endfor %}
    <br><br>
    <form method ="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'teachers:view_result' assignments.pk %}" role="button" class="btn btn-primary">Back</a>
    </form>
{% endblock content %}

templates/teachers/view_result.html
{% extends 'base.html' %}

{% block title %}{{ assignments.name }}{% endblock title %}

{% block content %}
    <h2 class="mb-3">Answers</h2>
    <div class='card'>
        <table class="table mb-0">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Roll no</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for asn in answered_student %}
                    <tr>
                        <td class="align-middle">{{ asn.student.user.username }}</td>
                        <td class="align-middle">{{ asn.student.roll_no }}</td>
                        <td class="align-middle"><a href="{% url 'teachers:view_result_student' assignments.pk asn.pk %}" class="btn btn-primary" role="button">View Answers</a></td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>No answers submitted!</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}