NAS/urls.py
from django.contrib import admin
from django.urls import path, include

from classroom.views import studentsignup, teachersignup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classroom.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/student/', studentsignup, name='student_signup'),
    path('accounts/signup/teacher/', teachersignup, name='teacher_signup'),
]

classroom/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    home,
    StudentAssignmentListView,
    take_assignment,
    submit_answer,
    AssignmentListView,
    AssignmentCreateView,
    AssignmentDeleteView,
    AssignmentUpdateView,
    view_result,
    view_answer,
    question_add,
    question_change,
    QuestionDeleteView,
)

urlpatterns = [
    path("", home, name="home"),
    path(
        "students/",
        include(
            (
                [
                    path(
                        "", StudentAssignmentListView.as_view(), name="assignment_list"
                    ),
                    path(
                        "assignment/<int:pk>/", take_assignment, name="take_assignment"
                    ),
                    path(
                        "assignment/<int:pk>/submit",
                        submit_answer,
                        name="submit_answer",
                    ),
                ],
                "classroom",
            ),
            namespace="students",
        ),
    ),
    path(
        "teacher/",
        include(
            (
                [
                    path(
                        "", AssignmentListView.as_view(), name="assignment_change_list"
                    ),
                    path(
                        "assignment/add/",
                        AssignmentCreateView.as_view(),
                        name="assignment_add",
                    ),
                    path(
                        "assignment/<int:pk>/",
                        AssignmentUpdateView.as_view(),
                        name="assignment_change",
                    ),
                    path(
                        "assignment/<int:pk>/delete/",
                        AssignmentDeleteView.as_view(),
                        name="assignment_delete",
                    ),
                    # path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
                    path(
                        "assignment/<int:pk>/result/", view_result, name="view_result"
                    ),
                    path(
                        "assignment/<int:assignments_pk>/result/<int:asn_pk>/",
                        view_answer,
                        name="view_result_student",
                    ),
                    path(
                        "assignment/<int:pk>/question/add/",
                        question_add,
                        name="question_add",
                    ),
                    path(
                        "assignment/<int:assignment_pk>/question/<int:question_pk>/",
                        question_change,
                        name="question_change",
                    ),
                    path(
                        "assignment/<int:assignment_pk>/question/<int:question_pk>/delete/",
                        QuestionDeleteView.as_view(),
                        name="question_delete",
                    ),
                ],
                "classroom",
            ),
            namespace="teachers",
        ),
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Online Assignment Submission"
admin.site.site_title = "OAS Admin Login"
admin.site.index_title = "Welcome to Online Assignment Submission Portal"

templates/students/assignment_list.html
{% extends 'base.html' %}

{% block title %}{{ user.username }} - Dashboard{% endblock title %}

{% block content %}
    <div class='card'>
        <table class= 'table mb-0'>
            <thead>
                <tr>
                <th>Assignment</th>
                <th>Subject</th>
                <th>Submission Date</th>
                <th>Remarks</th>
                </tr>
            </thead>
            <tbody>
                {% for assign in assignments %}
                <tr>
                    {% if assign.submission_date < timen %}
                        <td class="align-middle"><del>{{ assign.name }}</del></td>
                        <td class="align-middle"><del>{{ assign.subject }}</del></td>
                        <td class="align-middle"><del>{{ assign.submission_date }}</del></td>
                        {% for remark in remarks %}
                            {% if remark.studentanswer.assignment_id == assignment.id %}
                                <td>{{ remark.remark }}</td>
                            {% endif %}
                        {% empty %}
                            <td>No remarks provided.</td>
                        {% endfor %}
                    {% else %}
                        <td class="align-middle"><a href="{% url 'students:take_assignment' assign.pk %}">{{ assign.name }}</a></td>
                        <td class="align-middle">{{ assign.subject }}</td>
                        <td class="align-middle">{{ assign.submission_date }}</td>
                        {% for remark in remarks %}
                            {% if remark.studentanswer.assignment_id == assignment.id %}
                                <td>{{ remark.remark }}</td>
                            {% endif %}
                        {% empty %}
                            <td>No remarks provided.</td>
                        {% endfor %}
                    {% endif %}
                </tr>
                {% empty %}
                <tr>
                    <td class="bg-light text-center font-italic" colspan="4">No quiz matching your interests right now.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

templates/students/submit_answer.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} {{ assignments.name }} {% endblock title %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        {{ file_form|crispy }}
        <button type="submit" class="btn btn-success">Upload</button>
        <a href="{% url 'students:take_assignment' assignments.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
    </form>
{% endblock content %}

templates/students/take_assignment.html
{% extends 'base.html' %}

{% block title %} {{ assignments.name }}{% endblock title %}

{% block content %}
    <h3 class="mb-3">{{ assignments.name }}</h3>
    {% for q in question %}
        {{ q.text }}<br>
    {% endfor %}
    <br>
    {% for qq in questionimages %}
        <img src="/media/{{ qq.question_image }}" class="img-responsive" style="width:32%; height:60%;"/>
    {% empty %}

    {% endfor %}
    <br><br><br>
    <a href="{% url 'students:assignment_list' %}" class="btn btn-primary" role="button">Back</a>
    <a href="{% url 'students:submit_answer' assignments.pk%}" class="btn btn-primary" role="button">Submit Answers</a>
{% endblock content %}